<?php
/*
Plugin Name: Mozajik Loader
Plugin URI: http://www.mozajik.org/
Description: Mozajik Loader allows you to connect your Wordpress blog with the Mozajik Framework. Make sure to use the latest version of Mozajik and this plugin!
Version: 1.0
Author: Aron Budinszky <aron@mozajik.org>
Author URI: http://www.mozajik.org/
License: GPL2
@todo Add header template setting.
@todo Add option to turn javascripts on or off.
@todo Add option to load up mootools or jquery version.
*/

/**
 * Create my plugin options.
 **/ 
add_option('mozajik_options', array(
	'install_path'=>'', 	// Specifies the root path to the Mozajik installation to be used. This needs to be a full path (not realtive to Wordpress).
	'base_url'=>'',			// Specifies the base url to use in the Mozajik installation. If not specified, the baseurl will not be overridden and automatically be set.
	'init_controller'=>'',	// If specified, this controller will be run each time the application is initialized. It is like Mozajik's __load() method for this Wordpress site.
));

/**
 * Initializes a connection to the Mozajik system so it can run within Wordpress.
 **/
function mozajik_init(){
	$value = true;
	// Load up my settings
		$options = get_option('mozajik_options');
	// Make sure path is not a remote file
		if(empty($options['install_path']) || !preg_match("/^[A-z\/.]+$/", $options['install_path'])) return false;
	// Validate Mozajik path
		if(!file_exists($options['install_path'].'site/index.php')) return false;
		
	// My init vars need to be in global scope!
		global $zajconf, $zajlib;
	// Set to include mode (include mode disables js log messages and the exit() in Mozajik)
		$zaj_include_mode = true;
	// Fake a proper htaccess version request
		$_REQUEST['zajhtver'] = 10000;
	// Load up my index.php for Mozajik
		include_once($options['install_path'].'site/index.php');
	// Check if old config file
		if(!is_array($zajconf)){ echo "Mozajik failed to load up. Please use version 305 or higher config file!"; return false; }
	// If I have an init controller, reroute to it now!
		if(!empty($options['init_controller']) && preg_match("/^[A-z\/_]+$/", $options['init_controller'])){
			$value = $GLOBALS['zajlib']->reroute($options['init_controller']);
		}
	// If base url set, override my own
		if(!empty($options['base_url'])) $GLOBALS['zajlib']->baseurl = $options['base_url'];
	// Now turn off autoloading
		$GLOBALS['zajlib']->model_autoloading = false;
	return $value;
}
add_action('init', 'mozajik_init');

/**
 * This generates the includes for css, js, and other stuff needed for Mozajik to run properly.
 **/
function mozajik_head(){
	// Check if loaded properly
		if(!is_object($GLOBALS['zajlib'])){ echo "Mozajik failed to load up. Don't forget the proper settings in the admin panel!"; return false; }	
	// Load up javascript files
		echo '<script language="JavaScript" src="'.$GLOBALS['zajlib']->baseurl.'system/js/mootools/mootools-core-1.3.js" type="text/javascript"></script>';
		echo '<script language="JavaScript" src="'.$GLOBALS['zajlib']->baseurl.'system/js/mootools/mootools-more-1.3.js" type="text/javascript"></script>';
		echo '<script language="JavaScript" src="'.$GLOBALS['zajlib']->baseurl.'system/js/mozajik-base-1.3.js?v2" type="text/javascript"></script>';
	// Now load up my {{zaj.js}} variable to initialize Mozajik
		$zaj = $GLOBALS['zajlib']->template->get_variables();
		echo $zaj->js;
	return true;
}
add_action('wp_head', 'mozajik_head');

/**
 * This function can be used in templates to load up a Mozajik controller url. Any output generated by the controller will be displayed inline.
 * @param string $controller_url The url to the controller as relative to the baseurl of the Mozajik site.
 * @param array $additional_parameters An array of parameters to pass over to the controller function.
 **/
function mozajik_include($controller_url = '/', $additional_parameters = false){
	// Check if loaded properly
		if(!is_object($GLOBALS['zajlib'])){ echo "Mozajik failed to load up. Don't forget the proper settings in the admin panel!"; return false; }	
	// Turn on autoloading
		$GLOBALS['zajlib']->model_autoloading = true;	
	// Reroute to the specified controller
		$value = $GLOBALS['zajlib']->reroute($controller_url, $additional_parameters);
	// Turn off autoloading
		$GLOBALS['zajlib']->model_autoloading = false;
	return $value;
}

/**
 * This function can be used in templates to insert a Mozajik template file inline.
 * @param string $template_path The path to the template relative to the view folders.
 * @param string $block_name An optional block name which, if specified, will mean that only the given block's content will be displayed, not the entire template.
 **/
function mozajik_insert($template_path = 'base.html', $block_name = false){
	// Check if loaded properly
		if(!is_object($GLOBALS['zajlib'])){ echo "Mozajik failed to load up. Don't forget the proper settings in the admin panel!"; return false; }	
	// Turn on autoloading
		$GLOBALS['zajlib']->model_autoloading = true;	
	// Display the proper template
		if(!$block_name) $GLOBALS['zajlib']->template->show($template_path);
	// Display only the specific block of a template
		else $GLOBALS['zajlib']->template->block($template_path, $block_name);
	// Turn off autoloading
		$GLOBALS['zajlib']->model_autoloading = false;
	return true;
}

// Load up the admin settings interface.
include_once('mozajik-admin.php');


?>